import type { KanbanColumnKey, KanbanTask } from './types'

export const kanbanColumns: Array<{ key: KanbanColumnKey; label: string }> = [
  { key: 'todo', label: '할 일' },
  { key: 'doing', label: '진행 중' },
  { key: 'review', label: '검토 중' },
  { key: 'done', label: '완료' },
]

export const initialKanbanTasks: KanbanTask[] = [
  {
    id: 1,
    title: '경쟁사 UI 벤치마킹',
    category: '기획',
    categoryClass: 'tag-p',
    due: '~ 4/18',
    owner: '이수연',
    status: 'todo',
    description: '주요 경쟁 서비스 5개를 비교해서 IA, 온보딩, 협업 경험 차이를 정리합니다.',
  },
  {
    id: 2,
    title: '사용자 인터뷰 설계',
    category: '리서치',
    categoryClass: 'tag-t',
    due: '~ 4/20',
    owner: '김정현',
    status: 'todo',
    description: '인터뷰 대상자 기준과 핵심 질문 리스트를 정리하고 사전 스크립트를 작성합니다.',
  },
  {
    id: 3,
    title: '랜딩 페이지 카피 작성',
    category: '마케팅',
    categoryClass: 'tag-a',
    due: '~ 4/12 마감 초과',
    owner: '나',
    status: 'todo',
    overdue: true,
    description: '첫 방문 사용자가 5초 안에 제품 가치를 이해할 수 있도록 헤드라인과 서브카피를 다듬습니다.',
  },
  {
    id: 4,
    title: '프로토타입 1차 개발',
    category: '개발',
    categoryClass: 'tag-p',
    due: '~ 4/22',
    owner: '박준호',
    status: 'doing',
    description: '핵심 협업 흐름과 방 입장 경험을 우선 구현하고, 모바일 레이아웃도 함께 점검합니다.',
  },
  {
    id: 5,
    title: '기획서 v2 작성',
    category: '기획',
    categoryClass: 'tag-t',
    due: '~ 4/19',
    owner: '이수연',
    status: 'doing',
    description: '화면 흐름 업데이트와 함께 우선순위, 실험 범위, 검증 지표를 다시 정리합니다.',
  },
  {
    id: 6,
    title: '디자인 시스템 정의',
    category: '디자인',
    categoryClass: 'tag-a',
    due: '~ 4/16',
    owner: '김정현',
    status: 'review',
    description: '컬러, 타이포, 버튼, 입력창 규칙을 정리해서 이후 화면 작업에 재사용할 수 있게 합니다.',
  },
  {
    id: 7,
    title: '프로젝트 킥오프 미팅',
    category: '기획',
    categoryClass: 'tag-t',
    due: '완료',
    owner: '팀 전체',
    status: 'done',
    description: '프로젝트 목표와 역할 분담을 확정했습니다.',
  },
  {
    id: 8,
    title: '팀 온보딩 문서 공유',
    category: '기획',
    categoryClass: 'tag-p',
    due: '완료',
    owner: '나',
    status: 'done',
    description: '필수 문서와 작업 규칙을 팀에 공유했습니다.',
  },
]
